services:
  db:
    image: mysql:8.0
    container_name: financas_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financas
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: